//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPS.Resources.StringMessages", typeof(StringMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optum.
        /// </summary>
        public static string clientString_optum {
            get {
                return ResourceManager.GetString("clientString_optum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPSConnectionString.
        /// </summary>
        public static string EPSConnectionString {
            get {
                return ResourceManager.GetString("EPSConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose a Project--.
        /// </summary>
        public static string listItem_ChooseProject {
            get {
                return ResourceManager.GetString("listItem_ChooseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose a Client--.
        /// </summary>
        public static string listItem_ChooseProjectClient {
            get {
                return ResourceManager.GetString("listItem_ChooseProjectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose a Queue--.
        /// </summary>
        public static string listItem_ChooseProjectQueue {
            get {
                return ResourceManager.GetString("listItem_ChooseProjectQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select One--.
        /// </summary>
        public static string listItem_SelectOne {
            get {
                return ResourceManager.GetString("listItem_SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChartStatus.
        /// </summary>
        public static string lookup_ChartStatus {
            get {
                return ResourceManager.GetString("lookup_ChartStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommentCategory.
        /// </summary>
        public static string lookup_CommentCategory {
            get {
                return ResourceManager.GetString("lookup_CommentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCategory.
        /// </summary>
        public static string lookup_ErrorCategory {
            get {
                return ResourceManager.GetString("lookup_ErrorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string lookup_ErrorCategoryId {
            get {
                return ResourceManager.GetString("lookup_ErrorCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorSubcategory.
        /// </summary>
        public static string lookup_ErrorSubcategory {
            get {
                return ResourceManager.GetString("lookup_ErrorSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L3LevelDisagree.
        /// </summary>
        public static string lookup_L3LevelDisagree {
            get {
                return ResourceManager.GetString("lookup_L3LevelDisagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lookup_Location {
            get {
                return ResourceManager.GetString("lookup_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string ReferenceLabelHeading_Market {
            get {
                return ResourceManager.GetString("ReferenceLabelHeading_Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeInfo.
        /// </summary>
        public static string session_EmployeeInfo {
            get {
                return ResourceManager.GetString("session_EmployeeInfo", resourceCulture);
            }
        }
    }
}
