//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPS.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment description already exists..
        /// </summary>
        public static string CommentDescriptionAlreadyExists {
            get {
                return ResourceManager.GetString("CommentDescriptionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter MemberId.
        /// </summary>
        public static string EmptyClientReference_MMM {
            get {
                return ResourceManager.GetString("EmptyClientReference_MMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please limit your upload filesize to {0} charts..
        /// </summary>
        public static string ExceededBulkUploadLimit {
            get {
                return ResourceManager.GetString("ExceededBulkUploadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records deallocated successfully. Records Imported = {0}; Deleted records = {1}.
        /// </summary>
        public static string FileDeallocatedSuccessfully {
            get {
                return ResourceManager.GetString("FileDeallocatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Updated Successfully. Records Imported = {0}; Duplicate Records = {1}.
        /// </summary>
        public static string FileUploadedSuccessfully {
            get {
                return ResourceManager.GetString("FileUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the client project. Please contact your team lead..
        /// </summary>
        public static string InvalidAccessClientProject {
            get {
                return ResourceManager.GetString("InvalidAccessClientProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to upload the charts. Please contact your team lead..
        /// </summary>
        public static string InvalidAccessToUploadPage {
            get {
                return ResourceManager.GetString("InvalidAccessToUploadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data exists in uploaded excel file. Please correct and then Upload.
        /// </summary>
        public static string InvalidDataExistsInUpload {
            get {
                return ResourceManager.GetString("InvalidDataExistsInUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only excel files can be uploaded..
        /// </summary>
        public static string InvalidFileFormatForUpload {
            get {
                return ResourceManager.GetString("InvalidFileFormatForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied old password is invalid..
        /// </summary>
        public static string InvalidOldPassword {
            get {
                return ResourceManager.GetString("InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Excel layout has not been filled correctly. Please upload the appropriate excel file..
        /// </summary>
        public static string InvalidUploadFileSheetName {
            get {
                return ResourceManager.GetString("InvalidUploadFileSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the excel file..
        /// </summary>
        public static string NoExcelFileSelected {
            get {
                return ResourceManager.GetString("NoExcelFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been used in the previous ({0}) times. Please provide another password..
        /// </summary>
        public static string PasswordPreviouslyUsed {
            get {
                return ResourceManager.GetString("PasswordPreviouslyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a client..
        /// </summary>
        public static string RequiredClientProject {
            get {
                return ResourceManager.GetString("RequiredClientProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a project..
        /// </summary>
        public static string RequiredProject {
            get {
                return ResourceManager.GetString("RequiredProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a queue..
        /// </summary>
        public static string RequiredQueue {
            get {
                return ResourceManager.GetString("RequiredQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged on a different machine. Please logout first.
        /// </summary>
        public static string UserAlreadyLoggedOn {
            get {
                return ResourceManager.GetString("UserAlreadyLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have work in progress or pending charts in your queue. Please complete them before requesting for a new chart..
        /// </summary>
        public static string WIPChartsExist {
            get {
                return ResourceManager.GetString("WIPChartsExist", resourceCulture);
            }
        }
    }
}
